author: Matt1988
description: A general Classes plugin for use on the Project Xerocraft server.
generator: http://dinnerbone.com/minecraft/tools/pluginator/
main: me.matt.plugins.pxcclasses.Pxcclasses
name: PXC-Classes
startup: postworld
url: http://projectxerocraft.tk/
version: '0.1'

commands:
  Cast:
    aliases: [px, rp]
    description: The root command for Project Xerocraft
    usage: |
           /<command> help - Gets specific help for the PX-Classes plugin!
           /<command> help [command] gets help for a specific PX-Classes plugin command!